version: "3.8"
services:
  backstage:
    build:
      context: .
    environment:
      - PGDATABASE=backstage
      - POSTGRES_DATABASE=backstage
      - POSTGRES_HOST=localhost
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
    # ports:
    #   - 7007:7007
    depends_on:
      - postgres
    network_mode: host

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=backstage
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    # ports:
    #   - 5432:5432
    network_mode: host

volumes:
  pgdata: {}
